### ISSUE TITLE
Terms of service / Privacy policy

### ISSUE THREAD

**Issue by Browne** [not-so-creative/eisenhower#23]
ToS and PP are not available on any other page than the sign up screen. It would be desirable for users to be able to access this information - readily. 
- [x] Write and agree on a policy
- [x] Discussion on page layout i.e. where it fits in
  - [x] Implement changes

**Comment by fuzzyfox** [comment]
[ ] Add links to legal doc(s) to site footer

**Comment by Browne** [comment]
Closed: All changes are on a current pull request.
